[[section-introduction-and-goals]]
== Introduction and Goals

[role="arc42help"]
****
The application our team is developing aims to be a messenger app such as WhatsApp, with the main difference that ours will use a decentralized architecture to store the data. Since the storage and the app will be independent, it will be a more secure system than those similar to it.

Even though it will be a different approach to an existing technology, we expect to implement the same features as its brother systems. Some of these features include

* Notifications to start a chat
* Group chats
* File sharing

We also expect the end users to be able to use our app the same way they use the existing ones.
****

=== Requirements Overview

[role="arc42help"]
****
DeChat's goal is to yield a more secure chatting experience to all users while maintining the ease of use of the app.

****

=== Quality Goals

[role="arc42help"]
****
.Contents
When considering the application's future and considering stakeholders, I think there are three main quality attributes that we should keep in mind or consider over the rest. Those are:

* Scalability: In every application in which the number of users can grow out of control so easy(an this is exactly the case, as it is a   chat), the most important thing is to be prepared to handle fast increases in the number of people using the application, so preapare   both the software and the hardware to scale is essential.
  
* Availability: The application should also be ready at any time, users won't rely on something that is only available randomly,
  as they may need to contact with someone urgently, or need to have a read or a look at something that they had in a cnversation,
  so the application must be ready to always be up.
  
* Performance: Last but not least, performace is also a key factor. If every time we want to send or receive a message, we need to wait   for unreasonable periods of time, users will flee. Response times must be between some margins and kept as low as possible.

.Motivation
You should know the quality goals of your most important stakeholders, since they will influence fundamental architectural decisions. Make sure to be very concrete about these qualities, avoid buzzwords.
If you as an architect do not know how the quality of your work will be judged …

.Form
A table with quality goals and concrete scenarios, ordered by priorities
****

=== Stakeholders

[role="arc42help"]
****
.Contents
Explicit overview of stakeholders of the system, i.e. all person, roles or organizations that

* should know the architecture
* have to be convinced of the architecture
* have to work with the architecture or with code
* need the documentation of the architecture for their work
* have to come up with decisions about the system or its development

.Motivation
You should know all parties involved in development of the system or affected by the system.
Otherwise, you may get nasty surprises later in the development process.
These stakeholders determine the extent and the level of detail of your work and its results.

.Form
Table with role names, person names, and their expectations with respect to the architecture and its documentation.
****

[options="header",cols="1,2,2"]
|===
|Role/Name|Contact|Expectations
| _<Role-1>_ | _<Contact-1>_ | _<Expectation-1>_
| _<Role-2>_ | _<Contact-2>_ | _<Expectation-2>_
|===
