dist: trusty
sudo: false
 
language: node_js
node_js:
  - 10
 
addons:
  chrome: stable
      
cache:
  directories:
     - ./node_modules

install:
   - npm install
 
script:
  - npm install
  - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  
after_success:
  - npm run coverage
