dist: trusty
sudo: true
 
matrix:
  include:
    

    - language: node_js
      node_js:
        - 10
      addons:
        chrome: stable
      cache:
      directories:
        - ./node_modules/
        - ./node_modules/.bin/cucumber-js
      install:
        - npm install
        - npm install --save-dev @angular-devkit/build-angular
      script:
        - npm run e2e -- --no-watch --no-progress --browsers=ChromeHeadlessCI
        - jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
      after_success:
        - npm run e2e

    
