dist: trusty
sudo: true
 
matrix:
  include:
    

    - language: node_js
      node_js:
        - 10
      addons:
        chrome: stable
      cache:
      directories:
        - ./node_modules/
        - ./node_modules/.bin/cucumber-js
      install:
        - npm install
        - npm install --save-dev @angular-devkit/build-angular
      script:
        - nyc npm run e2e && nyc report --reporter=text-lcov | coveralls
      after_success:
        - npm run e2e

    
