dist: trusty
sudo: false
 
matrix:
  include:
    - language: python
      python: 
        - 2.7
      addons:
        chrome: stable
        before_install:
        - # start your web application and listen on `localhost`
        - google-chrome-stable --headless --disable-gpu --remote-debugging-port=4200 http://localhost &
      before_script:
        - "export DISPLAY=:99.0"
      install: 
        - pip install selenium
        - wget -N http://chromedriver.storage.googleapis.com/2.46/chromedriver_linux64.zip -P ~/
        - unzip ~/chromedriver_linux64.zip -d ~/
        - rm ~/chromedriver_linux64.zip
        - sudo mv -f ~/chromedriver /usr/local/share/
        - sudo chmod +x /usr/local/share/chromedriver
      script:
        - python seleniumtests.py

    - language: node_js
      node_js:
        - 10
      addons:
        chrome: stable
      cache:
      directories:
        - ./node_modules/
        - ./node_modules/.bin/cucumber-js
      install:
        - npm install
        - npm install --save-dev @angular-devkit/build-angular
      script:
        - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      after_success:
        - npm run e2e
