= dechat_en3b

image:https://travis-ci.org/Arquisoft/dechatjs_0.svg?branch=master["Build Status", link="https://travis-ci.org/Arquisoft/dechatjs_0"]
image:https://coveralls.io/repos/github/Arquisoft/dechatjs_0/badge.svg["Coverage status", link="https://coveralls.io/github/Arquisoft/dechatjs_0"]
image:https://api.codacy.com/project/badge/Grade/da6fef0ea42a4139b6a7535530ce3466["Codacy code quality", link="https://www.codacy.com/app/jelabra/dechatjs_0?utm_source=github.com&utm_medium=referral&utm_content=Arquisoft/dechatjs_0&utm_campaign=Badge_Grade"]
image:https://inch-ci.org/github/arquisoft/dechatjs_0.svg?branch=master["Docs", link="https://inch-ci.org/github/arquisoft/dechatjs_0"]

Skeleton of application using Javascript technologies

== Running tests

It requires link:http://nodejs.org[NodeJs] and `npm` (npm comes with NodeJs).

----
npm test
----

== Generating documentation

The skeleton documentation is based on link:http://arc42.org[arc42] templates.
Some diagrams are created using link:http://plantuml.com/[PlantUML].

Pre-requisites

- Install link:https://www.graphviz.org/[Graphviz] and ensure that the `dot` executable can be found in the PATH.

- Install `gulp` using:

----
npm install -g gulp
----

Once installed, running `gulp` creates the documentation.

----
gulp
----

Generates documentation in `docs` folder.

## Development server

Run `ng serve` for a dev server. Navigate to `http://localhost:4200/`. The app will automatically reload if you change any of the source files.

## Code scaffolding

Run `ng generate component component-name` to generate a new component. You can also use `ng generate directive|pipe|service|class|guard|interface|enum|module`.

## Build

Run `ng build` to build the project. The build artifacts will be stored in the `dist/` directory. Use the `--prod` flag for a production build.

## Running unit tests

Run `ng test` to execute the unit tests via [Karma](https://karma-runner.github.io).

## Running end-to-end tests

Run `ng e2e` to execute the end-to-end tests via [Protractor](http://www.protractortest.org/).

## Further help

To get more help on the Angular CLI use `ng help` or go check out the [Angular CLI README](https://github.com/angular/angular-cli/blob/master/README.md).
