= dechat_en3b

image:https://travis-ci.org/Arquisoft/dechat_en3b.svg["Build Status", link="https://travis-ci.org/Arquisoft/dechat_en3b"]
image:https://coveralls.io/repos/github/Arquisoft/dechat_en3b/badge.svg?branch=master["Coverage status", link="https://coveralls.io/github/Arquisoft/dechat_en3b"]
image:https://api.codacy.com/project/badge/Grade/da6fef0ea42a4139b6a7535530ce3466["Codacy code quality", link="https://www.codacy.com/app/jelabra/dechat_en3b?utm_source=github.com&utm_medium=referral&utm_content=Arquisoft/dechat_en3b&utm_campaign=Badge_Grade"]
image:https://img.shields.io/badge/docs-arc42-9cf.svg["Documentation",link="https://arquisoft.github.io/dechat_en3b/docs"]
image:https://img.shields.io/npm/l/protractor-cucumber-steps.svg["License", link="https://github.com/Arquisoft/dechat_en3b/blob/master/LICENSE"]
image:https://img.shields.io/badge/project-Solid-7C4DFF.svg?style=flat-square["Solid", link="https://github.com/solid/solid"]

== Application & Documentation
link:https://arquisoft.github.io/dechat_en3b/[Application],
link:https://arquisoft.github.io/dechat_en3b/docs[Documentation].


== Running tests

It requires link:http://nodejs.org[NodeJs] and `npm` (npm comes with NodeJs). Also Cucumber and Chai for the new tests.

----
ng e2e
----

== Generating documentation

The skeleton documentation is based on link:http://arc42.org[arc42] templates.
Some diagrams are created using link:http://plantuml.com/[PlantUML].

Pre-requisites

- Install link:https://www.graphviz.org/[Graphviz] and ensure that the `dot` executable can be found in the PATH.

- Install `gulp` using:

----
npm install -g gulp
----

Once installed, running `gulp` creates the documentation.

----
gulp
----

Generates documentation in `docs` folder.

## Development server

Run `npm run start` for a dev server. The app will automatically reload if you change any of the source files.

## Code scaffolding

Run `ng generate component component-name` to generate a new component. You can also use `ng generate directive|pipe|service|class|guard|interface|enum|module`.

## Build

Run `ng build` to build the project. The build artifacts will be stored in the `dist/` directory. Use the `--prod` flag for a production build.

## Running end-to-end tests

Run `ng e2e` to execute the end-to-end tests via link:http://www.protractortest.org/[Protractor].

## Further help

To get more help on the Angular CLI use `ng help` or go check out the link:https://github.com/angular/angular-cli/blob/master/README.md[Angular CLI README].
