= dechat_en3b

image:https://travis-ci.org/Arquisoft/dechat_en3b.svg["Build Status", link="https://travis-ci.org/Arquisoft/dechat_en3b"]
image:https://coveralls.io/repos/github/Arquisoft/dechat_en3b/badge.svg?branch=master["Coverage status", link="https://coveralls.io/github/Arquisoft/dechat_en3b"]
image:https://api.codacy.com/project/badge/Grade/da6fef0ea42a4139b6a7535530ce3466["Codacy code quality", link="https://www.codacy.com/app/jelabra/dechat_en3b?utm_source=github.com&utm_medium=referral&utm_content=Arquisoft/dechat_en3b&utm_campaign=Badge_Grade"]
image:https://img.shields.io/badge/docs-arc42-9cf.svg["Documentation",link="https://arquisoft.github.io/dechat_en3b/docs"]
image:https://img.shields.io/npm/l/protractor-cucumber-steps.svg["License", link="https://github.com/Arquisoft/dechat_en3b/blob/master/LICENSE"]
image:https://img.shields.io/badge/project-Solid-7C4DFF.svg?style=flat-square["Solid", link="https://github.com/solid/solid"]

== Try the app
With link:https://arquisoft.github.io/dechat_en3b/[this link], you can access to the last built version of DeChat.


== Running tests

There are two sets of tests, the ones integrated with Travis (Cucumber) and some Web Browser ones using Selenium which we could not make to work with Travis.

To run the first ones:
It requires link:http://nodejs.org[NodeJs] and `npm` (npm comes with NodeJs). Also Cucumber and Chai for the new tests.

----
ng e2e
----

To run the Selenium ones, you would need link:https://chromedriver.storage.googleapis.com/75.0.3770.90/chromedriver_win32.zip[chromedriver], and to specify its path in the link:https://github.com/Arquisoft/dechat_en3b/blob/master/seleniumtests.py[Selenium tests] file. Then, simply

----
python seleniumtests.py
----
Note: These tests were developed using link:https://www.python.org/downloads/release/python-2715/[Python 2.7.15]

== Generating documentation

The skeleton documentation is based on link:http://arc42.org[arc42] templates.
Some diagrams are created using link:http://plantuml.com/[PlantUML].

Pre-requisites

- Install link:https://www.graphviz.org/[Graphviz] and ensure that the `dot` executable can be found in the PATH.

- Install `gulp` using:

----
npm install -g gulp
----

Once installed, running `gulp` creates the documentation.

----
gulp
----

Generates documentation in `docs` folder.

## Development server

Run `npm run start` for a dev server. The app will automatically reload if you change any of the source files.

## Code scaffolding

Run `ng generate component component-name` to generate a new component. You can also use `ng generate directive|pipe|service|class|guard|interface|enum|module`.

## Build

Run `ng build` to build the project. The build artifacts will be stored in the `dist/` directory. Use the `--prod` flag for a production build.

## Deployment

To deploy the application we created a simple script which will build the app, generate the documentation and place everything in the correct paths so that it can be deployed with a single commit to GitHub Pages.
To do this: 

----
npm run dad
----
Then you just need to rename link:https://github.com/Arquisoft/dechat_en3b/blob/master/docs/index.html[this file] to "404.html" instead and push the commit. It might take sometime to build it, and sometime for GitHub to process it.

## Running end-to-end tests

Run `ng e2e` to execute the end-to-end tests via link:http://www.protractortest.org/[Protractor].

## Further help

To get more help on the Angular CLI use `ng help` or go check out the link:https://github.com/angular/angular-cli/blob/master/README.md[Angular CLI README].
