export function checkSession(): any;
export function copyFile(oldFile: any, newFile: any): void;
export function copyFolder(src: any, dest: any, options: any, indent: any): any;
export function createFile(url: any, content: any, contentType: any): any;
export function createFolder(url: any): any;
export function deleteFile(url: any): any;
export function deleteFolder(url: any): any;
export function downloadFile(url: any, localPath: any): any;
export function fetch(url: any, request: any): any;
export function fetchAndParse(url: any, contentType: any): any;
export function getCredentials(fn: any): any;
export function guessFileType(url: any): any;
export function login(credentials: any): any;
export function logout(): any;
export function popupLogin(): any;
export function processFolder(graph: any, url: any, content: any): any;
export function readFile(url: any): any;
export function readFolder(url: any): any;
export function text2graph(text: any, url: any, contentType: any): any;
export function updateFile(url: any, content: any, contentType: any): any;
export function uploadFile(fn: any, url: any): any;
